### PR TITLE
support triggering observers

### PR DESCRIPTION
**Pull request by extrawurst**
* deprecate `EventWriter` solution (any reason to keep it around and not deprecate?)
* warn that you should not use both ways for the same event type

### CODE REVIEW

**Comment by johanhelsing** [comment]
What do triggers do? Is it a new thing?

**Comment by extrawurst** [comment]
yeah its the new observer system that arrived in bevy 0.14, read more about it here:

* https://bevyengine.org/news/bevy-0-14/#ecs-hooks-and-observers
* https://github.com/bevyengine/bevy/blob/main/examples/ecs/observers.rs

**Comment by johanhelsing** [comment]
> * deprecate `EventWriter` solution (any reason to keep it around and not deprecate?)

Thanks, I totally missed that section of the release post.

OK, so as far as I can see triggers have the following advantages:

## pros

- Can handle events directly when polling the channel in PreUpdate
- Easier to avoid unintended 1-frame delay if you need to process in PreUpdate

## cons

- More boiler-plate if you want to handle the event in another schedule (like Update)

Unfortunately, I think handling events in Update is probably the most common use-case? We don't want to make that more complicated

**Comment by extrawurst** [comment]
ok the question is then, do we just support both or do you not want to support observers?

**Comment by extrawurst** [comment]
Closing in favor of https://github.com/rustunit/bevy_channel_trigger

**Pull request closed without merging**
